puts "The students of my cohort at Makers Academy"
puts "-------------------------"
puts "Ruben Kostucki"
puts "Mihai Cojocar"
puts "Andy Gates"
puts "Henry Stanley"
puts "Alex Peattie"	
puts "Vincent Koch"	
puts "Nick Rhys"	
puts "Lovis Schultze"	
puts "Spike L"
puts "Mark Singh"
puts "Faisal Aydarus"
puts "Kevin Daniells"
puts "Merve Silk"
puts "Maya Driver"	
puts "Ethel Ng"
puts "Benjamin Tillett"
puts "David Wickes"
puts "Michelle Ballard"
puts "James McNeil"
puts "Chris Oatley"	
puts "Jerome Pratt"
puts "Ruth Earle"
puts "Javier Silverio"	
puts "Stephen Lloyd"
puts "Leopold Kwok"